<main class="container">
    <h2>Bonjour <?= htmlspecialchars($_SESSION['admin']) ?></h2>
    <ul>
        <li><a href="openingHoursForm">Gestion des Horaires</a></li>
        <li><a href="meals">Gestion des plats</a></li>
        <li><a href="booking">Gestion des Réservations</a></li>
        <li><a href="menus">Gestion des Menus</a></li>
        <li><a href="categories">Gestion des catégories</a></li>
        <!--<a href="Comments">Gestion des commentaires</h3>-->
    </ul>
</main>
