<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Freshly Restaurant, your new favourite restaurant !">
	<title>Freshly Restaurant - Home</title>
	<link rel="icon" href="assets/favicon.png">
	<link href="https://fonts.googleapis.com/css?family=Athiti:500|Merienda:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="assets/css/slick.css">
	<link rel="stylesheet" href="assets/css/slick-theme.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
	<link rel="stylesheet" href="assets/css/style.css">
</head>

<body>
	<header>
		<div class="container">
			<a href="index.php" class="logo">
				<img src="assets/img/logo.png" alt="Logo for Freshly Restaurant">
				<strong>Freshly Restaurant</strong>
			</a>
			<nav>
				<ul>
					<li><a href="index.php" class="active">Home</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="menus.html">Menus</a></li>
					<li><a href="contact.html">Contact</a></li>
					<?php if(!isset($_SESSION['admin']) && !isset($_SESSION['users'])): ?>
					    <li><a href="login">Log In</a></li>
					<?php endif; ?>
					<?php if(isset($_SESSION['admin'])): ?>
					    <li><a href="Back-Office">Back Office</a></li>
				    <?php endif; ?>
				    <?php if(isset($_SESSION['users'])): ?>
					    <li><a href="Book">Réservation</a></li>
				    <?php endif; ?>
				    <?php if(isset($_SESSION['admin']) || isset($_SESSION['users'])): ?>
					    <li><a href="index.php?action=deco">Log Out</a></li>
				    <?php endif; ?>
					
				</ul>
			</nav>
		</div> <!-- end of .container -->
	</header>
	
		<!-- code principal de la page -->
    	<?php include $template ?>
    	
	<footer>
		<div class="container">
			<div class="flex">
				<aside>
					<h4>Opening hours</h4>
					<ul>
						<li>Monday: Closed</li>
						<li>Tue-Wed : 9am - 10pm</li>
						<li>Thu-Fri : 9am - 10pm</li>
						<li>Sat-Sun : 5pm - 10pm</li>
					</ul>
				</aside>
				<aside>
					<h4>Contact</h4>
					<address>
						<p>13 Christopher Street<br>
							New York,<br>
							NY 10014-3543</p>
						<p>+01 2000 800 9999</p>
					</address>
				</aside>
				<aside>
					<h4>Social networks</h4>
					<div class="reseaux">
						<a href="#" class="fab fa-facebook-f"></a>
						<a href="#" class="fab fa-instagram"></a>
						<a href="#" class="fab fa-pinterest-p"></a>
					</div>
				</aside>
			</div> <!-- end of .flex -->
		</div> <!-- end of .container -->
	</footer>
	<!-- Charger la bibliothèque de base de jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<!-- Charger le script du plugin -->
	<script src="assets/js/slick.min.js"></script>
	<!-- Indiquer sur quel élément de la page on applique le plugin -->
	<script>
		$(document).ready(function () {
			$('.slider').slick({
				dots: true
			});
		});
	</script>
</body>

</html>