<main class="container mixitup">
		<h1>Details of our menus</h1>
		<p class="select">Choose your main course according to your menu!</p>
		<div class="filter">
			<button data-filter="all">All</button>
			
			<?php foreach($categories as $cat): ?>
				<button data-filter=".<?= lcfirst($cat['name']) ?>"><?= $cat['name'] ?></button>
			<?php endforeach; ?>
			
		</div> <!-- end of .filter -->
		<div class="choice">
		<?php foreach($meals as $meal): ?>
				<div class="mix <?= lcfirst($meal['cName']) ?>"><!-- a voir -->
					<figure>
						<img src="<?= $meal['src'] ?>" alt="<?= $meal['alt'] ?>">
						<figcaption><img src="assets/img/fork-knife.svg" alt="">
							<h3><?= $meal['name'] ?></h3>
						</figcaption>
					</figure>
				</div>
			
		<?php endforeach; ?>
		</div> <!-- end of .choice -->
			<?php foreach($others as $other): ?>
				<article>
					<h2><?= $other['name'] ?></h2>
					<p class="select"><?= $other['description'] ?></p>
					<div class="choice">
						<?php foreach($this -> getOthersById($other['id']) as $meal): ?>
							<figure>
								<img src="<?= $meal['src'] ?>" alt="<?= $meal['alt'] ?>">
								<figcaption><img src="assets/img/fork-knife.svg" alt="">
									<h3><?= $meal['name'] ?></h3>
								</figcaption>
							</figure>
					<?php endforeach; ?>
				</article>
			<?php endforeach; ?>
		</div> <!-- end of .choice -->
	</main>