<main class="container mixitup">
		<h1>Details of our menus</h1>
		<p class="select">Choose your main course according to your menu!</p>
		<div class="filter">
			<button data-filter="all">All</button>
			<button data-filter=".meat">Meat</button>
			<button data-filter=".vegan">Vegan</button>
			<button data-filter=".fish">Fish</button>
		</div> <!-- end of .filter -->
		<div class="choice">
			<div class="mix meat">
				<figure>
					<img src="img/menus/meat-01.jpg" alt="One big burger">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Freshly burger</h3>
					</figcaption>
				</figure>
			</div>
		</div> <!-- end of .choice -->
		<article>
			<h2>Deserts</h2>
			<p class="select">Here are the deserts you can choose to finish your meal (included in your menu).</p>
			<div class="choice">
				<figure>
					<img src="img/menus/desert-01.jpg" alt="A plate with a tiramisu">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Tiramisu</h3>
					</figcaption>
				</figure>
			</div> <!-- end of .choice -->
		</article>
		<article>
			<h2>Cocktails</h2>
			<p class="select">Soft drinkgs are included, but if you want you can order one of our excellent cocktails (not included in the menu).</p>
			<div class="choice">
				<figure>
					<img src="img/menus/drink-01.jpg" alt="cocktail drink">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Winter Whiskey</h3>
					</figcaption>
				</figure>
			</div> <!-- end of .choice -->
		</article>
	</main>